import {
  Activity,
  BarChart3,
  CheckCircle,
  FolderGit2,
  Target,
  TrendingUp,
} from "lucide-react";

import {
  assignedIssues,
} from "../../utils/helpers/repository";

import {
  repositoryHealth,
} from "../../utils/helpers/prediction";

import ConfidenceGauge from "../charts/ConfidenceGauge";
import IssueDistribution from "../charts/IssueDistribution";
import RepositoryHealthChart from "../charts/RepositoryHealthChart";

import StatisticsCard from "./StatisticsCard";
import StatisticsGrid from "./StatisticsGrid";

interface RepositoryOverviewProps {
  repository: string;
  totalIssues: number;
  availableIssues: number;
  averageConfidence: number;
}

export default function RepositoryOverview({
  repository,
  totalIssues,
  availableIssues,
  averageConfidence,
}: RepositoryOverviewProps) {
  const totalAssigned = assignedIssues(
    totalIssues,
    availableIssues,
  );

  const health = repositoryHealth(
    averageConfidence,
  );

  return (
    <section className="space-y-8">
      {/* Dashboard Header */}

      <div className="overflow-hidden rounded-[2rem] border border-slate-200 bg-gradient-to-br from-slate-950 via-slate-900 to-blue-950 text-white shadow-[0_30px_70px_rgba(15,23,42,0.25)]">
        <div className="flex flex-col gap-6 p-8 lg:flex-row lg:items-center lg:justify-between lg:p-10">
          <div>
            <span className="inline-flex rounded-full border border-cyan-400/30 bg-white/10 px-4 py-2 text-sm font-semibold text-cyan-200 backdrop-blur">
              Repository Dashboard
            </span>

            <h2 className="mt-5 text-4xl font-black tracking-tight">
              {repository}
            </h2>

            <p className="mt-4 max-w-2xl text-lg leading-8 text-slate-300">
              Repository successfully analyzed. Browse
              intelligent insights, confidence metrics,
              contribution opportunities, and pull request
              predictions generated by IssueScout.
            </p>
          </div>

          <div className="rounded-3xl border border-white/10 bg-white/10 px-8 py-6 text-center backdrop-blur">
            <p className="text-sm uppercase tracking-widest text-slate-300">
              Repository Health
            </p>

            <h3 className="mt-2 text-4xl font-black text-cyan-300">
              {health}
            </h3>
          </div>
        </div>
      </div>

      {/* Statistics */}

      <StatisticsGrid>
        <StatisticsCard
          title="Repository"
          value={repository}
          icon={<FolderGit2 size={22} />}
          color="bg-indigo-100 text-indigo-600"
        />

        <StatisticsCard
          title="Total Issues"
          value={totalIssues}
          icon={<Activity size={22} />}
          color="bg-blue-100 text-blue-600"
        />

        <StatisticsCard
          title="Available"
          value={availableIssues}
          icon={<CheckCircle size={22} />}
          color="bg-green-100 text-green-600"
        />

        <StatisticsCard
          title="Assigned"
          value={totalAssigned}
          icon={<BarChart3 size={22} />}
          color="bg-orange-100 text-orange-600"
        />

        <StatisticsCard
          title="Average Confidence"
          value={`${averageConfidence}%`}
          icon={<Target size={22} />}
          color="bg-cyan-100 text-cyan-600"
        />

        <StatisticsCard
          title="Repository Health"
          value={health}
          icon={<TrendingUp size={22} />}
          color="bg-emerald-100 text-emerald-600"
        />
      </StatisticsGrid>

      {/* Analytics */}

      <div className="grid gap-6 lg:grid-cols-3">
        <div className="rounded-[1.75rem] border border-slate-200 bg-white p-6 shadow-sm transition-all duration-300 hover:shadow-lg">
          <ConfidenceGauge
            value={averageConfidence}
          />
        </div>

        <div className="rounded-[1.75rem] transition-all duration-300 hover:shadow-lg">
          <IssueDistribution
            assigned={totalAssigned}
            unassigned={availableIssues}
          />
        </div>

        <div className="rounded-[1.75rem] transition-all duration-300 hover:shadow-lg">
          <RepositoryHealthChart
            score={averageConfidence}
          />
        </div>
      </div>
    </section>
  );
}
