import {
  Activity,
  BarChart3,
  CheckCircle,
  FolderGit2,
  Sparkles,
  Target,
  TrendingUp,
} from "lucide-react";

import {
  assignedIssues,
} from "../../utils/helpers/repository";

import {
  repositoryHealth,
} from "../../utils/helpers/prediction";

import ConfidenceGauge from "../charts/ConfidenceGauge";
import IssueDistribution from "../charts/IssueDistribution";
import RepositoryHealthChart from "../charts/RepositoryHealthChart";

import StatisticsCard from "./StatisticsCard";
import StatisticsGrid from "./StatisticsGrid";

interface RepositoryOverviewProps {
  repository: string;
  totalIssues: number;
  availableIssues: number;
  averageConfidence: number;
}

export default function RepositoryOverview({
  repository,
  totalIssues,
  availableIssues,
  averageConfidence,
}: RepositoryOverviewProps) {

  const assigned = assignedIssues(
    totalIssues,
    availableIssues,
  );

  const health = repositoryHealth(
    averageConfidence,
  );

  return (

    <section className="space-y-6">

      {/* Repository Header */}

      <div className="rounded-3xl border border-slate-200 bg-white p-7 shadow-sm">

        <div className="flex flex-col gap-6 lg:flex-row lg:items-center lg:justify-between">

          <div>

            <div className="inline-flex items-center gap-2 rounded-full bg-blue-50 px-4 py-2 text-sm font-semibold text-blue-700">

              <Sparkles size={15} />

              AI Repository Intelligence

            </div>

            <h2 className="mt-4 text-3xl font-black text-slate-900">

              {repository}

            </h2>

            <p className="mt-3 max-w-2xl text-slate-600">

              Repository successfully analyzed.
              Browse repository health, issue statistics,
              contribution opportunities and prediction
              insights generated by IssueScout.

            </p>

          </div>

          <div className="grid grid-cols-2 gap-4">

            <div className="rounded-2xl bg-slate-50 px-5 py-4">

              <p className="text-xs uppercase tracking-wider text-slate-500">
                Repository
              </p>

              <p className="mt-2 font-bold text-slate-900">
                {repository}
              </p>

            </div>

            <div className="rounded-2xl bg-green-50 px-5 py-4">

              <p className="text-xs uppercase tracking-wider text-green-700">
                Health
              </p>

              <p className="mt-2 text-lg font-black text-green-700">
                {health}
              </p>

            </div>

          </div>

        </div>

      </div>

      {/* Statistics */}

      <StatisticsGrid>

        <StatisticsCard
          title="Repository"
          value={repository}
          icon={<FolderGit2 size={20} />}
          color="bg-indigo-100 text-indigo-600"
          subtitle="Repository scanned"
        />

        <StatisticsCard
          title="Issues"
          value={totalIssues}
          icon={<Activity size={20} />}
          color="bg-blue-100 text-blue-600"
          subtitle="Total open issues"
        />

        <StatisticsCard
          title="Available"
          value={availableIssues}
          icon={<CheckCircle size={20} />}
          color="bg-green-100 text-green-600"
          subtitle="Ready to contribute"
        />

        <StatisticsCard
          title="Assigned"
          value={assigned}
          icon={<BarChart3 size={20} />}
          color="bg-orange-100 text-orange-600"
          subtitle="Already assigned"
        />

        <StatisticsCard
          title="Confidence"
          value={`${averageConfidence}%`}
          icon={<Target size={20} />}
          color="bg-cyan-100 text-cyan-600"
          subtitle="Average AI score"
        />

        <StatisticsCard
          title="Health"
          value={health}
          icon={<TrendingUp size={20} />}
          color="bg-emerald-100 text-emerald-600"
          subtitle="Repository quality"
        />

      </StatisticsGrid>

      {/* Analytics */}

      <div className="grid gap-5 xl:grid-cols-3">

        <ConfidenceGauge
          value={averageConfidence}
        />

        <IssueDistribution
          assigned={assigned}
          unassigned={availableIssues}
        />

        <RepositoryHealthChart
          score={averageConfidence}
        />

      </div>

    </section>

  );

}
